WebSistemaPrestamos/WebSistemaPrestamos/Controllers/AdministradorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSistemaPrestamos.Models;
using WebSistemaPrestamos.Negocio;

namespace WebSistemaPrestamos.Controllers
{
    [Authorize]
    public class AdministradorController : Controller
    {
        // GET: Administrador
        public ActionResult Index()
        {
            int idup = (int)Session["IdSessionPadre"];
            ViewBag.IdUsuarioPadre = idup;
            return View();
        }

        [HttpGet]
        public JsonResult ListarUsuarioGeneral(int idpadre)
        {
            List<Usuario> olista = new List<Usuario>();
            olista = new CrudGeneralNegoc().ListarUsuariosPorPadre(idpadre);
            return Json(new { lista = olista }, JsonRequestBehavior.AllowGet);

        }



        [HttpPost]
        public JsonResult guardarusuariogeneral(Usuario obj)
        {
            object resultado = null;
            string mensaje = string.Empty;
            //Registrar
            if (obj.idusuario == 0)
            {
                resultado = new UsuarioNegoc().registrarusuariogenerl(obj, out mensaje);
            }
            //Editar
            else
            {
                resultado = new UsuarioNegoc().EditarUsuarioGEneral(obj, out mensaje);
            }
            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
    }
}

WebSistemaPrestamos/WebSistemaPrestamos/Controllers/InversionistaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSistemaPrestamos.Models;
using WebSistemaPrestamos.Negocio;
//Controlador de Inversionista
namespace WebSistemaPrestamos.Controllers
{
    [Authorize]
    public class InversionistaController : Controller
    {
      
        // GET: Inversionista
        public ActionResult Index()
        {
            int idup = (int)Session["IdSessionPadre"];
            ViewBag.IdUsuarioPadre = idup;

            return View();
        }

        [HttpGet]
        public JsonResult ListarUsuarioGeneral(int idpadre)
        {
            List<Usuario> olista = new List<Usuario>();
            olista = new CrudGeneralNegoc().ListarUsuariosPorPadre(idpadre);
            return Json(new { lista = olista }, JsonRequestBehavior.AllowGet);

        }



        [HttpPost]
        public JsonResult guardarusuariogeneral(Usuario obj)
        {
            object resultado=null;
            string mensaje = string.Empty;
            //Registrar
            if (obj.idusuario == 0)
            {
                resultado = new UsuarioNegoc().registrarusuariogenerl(obj, out mensaje);
            }
            //Editar
            else
            {
                resultado = new UsuarioNegoc().EditarUsuarioGEneral(obj, out mensaje);
            }
            return Json(new {resultado=resultado,mensaje= mensaje}, JsonRequestBehavior.AllowGet);
        }
    }
}

WebSistemaPrestamos/WebSistemaPrestamos/Controllers/PrestamistaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSistemaPrestamos.Models;
using WebSistemaPrestamos.Negocio;



//Controlador de Prestamo
namespace WebSistemaPrestamos.Controllers
{
    [Authorize]
    public class PrestamistaController : Controller
    {
        // GET: Prestamista
        public ActionResult Index()
        {
            int idup = (int)Session["IdSessionPadre"];
            ViewBag.IdUsuarioPadre = idup;
            return View();
        }


        public ActionResult AprobarPrestamos()
        {
          
            return View();
        }




        [HttpGet]
        public JsonResult ListarUsuarioGeneral(int idpadre)
        {
            List<Usuario> olista = new List<Usuario>();
            olista = new CrudGeneralNegoc().ListarUsuariosPorPadre(idpadre);
            return Json(new { lista = olista }, JsonRequestBehavior.AllowGet);

        }


        [HttpPost]
        public JsonResult guardarusuariogeneral(Usuario obj)
        {
            object resultado = null;
            string mensaje = string.Empty;
            //Registrar
            if (obj.idusuario == 0)
            {
                resultado = new UsuarioNegoc().registrarusuariogenerl(obj, out mensaje);
            }
            //Editar
            else
            {
                resultado = new UsuarioNegoc().EditarUsuarioGEneral(obj, out mensaje);
            }
            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }



        [HttpGet]
        public JsonResult ListarPrestamosGeneralPrestamista(int idusuariopadre)
        {
            List<Prestamo> olista = new List<Prestamo>();
            olista = new PrestamosNegoc().ListarPrestamosPrestamista(idusuariopadre);
            return Json(new { lista = olista }, JsonRequestBehavior.AllowGet);

        }

    }
}

WebSistemaPrestamos/WebSistemaPrestamos/Controllers/PrestatarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSistemaPrestamos.Models;
using WebSistemaPrestamos.Negocio;

//referencias para la api de paypal
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using Newtonsoft.Json;
using System.Threading.Tasks;
//Models de payapl
using WebSistemaPrestamos.Models.Paypal_Order;
using WebSistemaPrestamos.Models.Paypal_Transaction;

namespace WebSistemaPrestamos.Controllers
{

    [Authorize]
    public class PrestatarioController : Controller
    {
        // GET: Prestatario Principal
        public ActionResult Index()
        {

            int idup = (int)Session["IdSessionPadre"];
            ViewBag.IdUsuarioPadre = idup;

            //int idprestageneral = (int)Session["IdSessionPrestamista"];
            //ViewBag.IdPrestamiPadre= idprestageneral;

            return View();
        }

        public async Task<ActionResult> Abunt()
        {
            string token = Request.QueryString["token"];

            //  ViewData["IdTransaccion"] = "hola soy el jose data";
            //ViewData["Status"] = true;

            bool status = false;
              // Configurar las credenciales de autenticación de PayPal
                var userName = "AceDg6yf6zlibcKhUCnXzhpKZ78r_CpkfuCSRJJQ08uQGj8KIJcIwY-yHYIgBX9u2YILhGDRJCr_z9vu";
                var password = "EBE03zsi9ey0KQvX9SBPui-PKjeD2eTVHK418QZL6ut8dMxTD8EysI61xcjS91tZITim0KFec3AwJbqe";


                // Configurar la solicitud HTTP a la API de PayPal
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("https://api-m.sandbox.paypal.com");
                    var authToken = Encoding.ASCII.GetBytes($"{userName}:{password}");
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", Convert.ToBase64String(authToken));

                    var data = new StringContent("{}", Encoding.UTF8, "application/json");


                    // Realizar la solicitud POST a la API de PayPal
                    HttpResponseMessage response = await client.PostAsync($"/v2/checkout/orders/{token}/capture", data);

                    status = response.IsSuccessStatusCode;

                    if (status)
                    {
                    var jsonresult=response.Content.ReadAsStringAsync().Result;

                        Paypal_transaction objeto=JsonConvert.DeserializeObject<Paypal_transaction>(jsonresult);
                      //  ViewData["IdTransaccion"] = objeto.payment_source.paypal;
                    }
                    
                }
            
            

            return View();
        }


        public ActionResult Vermisprestamos()
        {     
            return View();
        }

        [HttpPost]
        public JsonResult guardarregistroprestamos(Prestamo obj)
        {
            object resultado = null;
            string mensaje=string.Empty;
            resultado=new PrestamosNegoc().RegistrarPrestamos(obj, out mensaje);
            return Json(new { resultado = resultado , mensaje=mensaje}, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult ListarPrestamosGeneral(int idusuario)
        {
            List<Prestamo> olista = new List<Prestamo>();
            olista = new PrestamosNegoc().ListarPrestamosPrestatario(idusuario);
            return Json(new { lista = olista }, JsonRequestBehavior.AllowGet);

        }

        [HttpGet]
        public JsonResult ListarDetallePrestamosGeneral(int idprestamo)
        {
            List<DetallePrestamo> olista = new List<DetallePrestamo>();
            olista = new DetallePrestamosNegoc().ListardetallePrestamos(idprestamo);
            return Json(new { lista = olista }, JsonRequestBehavior.AllowGet);

        }




        //[HttpPost]
        //public async Task<JsonResult> Paypal(string precio , string ncuota)
        //{
        //    bool status = false;
        //    string respuesta = string.Empty;

        //    using (var client=new HttpClient())
        //    {
        //        var userName = "AceDg6yf6zlibcKhUCnXzhpKZ78r_CpkfuCSRJJQ08uQGj8KIJcIwY-yHYIgBX9u2YILhGDRJCr_z9vu";
        //        var password = "EBE03zsi9ey0KQvX9SBPui-PKjeD2eTVHK418QZL6ut8dMxTD8EysI61xcjS91tZITim0KFec3AwJbqe";

        //        client.BaseAddress = new Uri("https://api-m.sandbox.paypal.com");

        //        var authToken = Encoding.ASCII.GetBytes($"{userName}:{password}");
        //        client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", Convert.ToBase64String(authToken));


        //        var orden = new PaypalOrder()
        //        {
        //            intent = "CAPTURE",
        //            purchase_units = new List<Models.Paypal_Order.PurchaseUnit>()
        //            {
        //                new Models.Paypal_Order.PurchaseUnit()
        //                {
        //                    items = new List<Models.Paypal_Order.Item>()
        //                    {
        //                        new Models.Paypal_Order.Item(){
        //                            name = "Numero de cuota " + ncuota,
        //                            description = "Sistema de Prestamo Grupo 8A Cibertec",
        //                            quantity = "1",
        //                            unit_amount = new Models.Paypal_Order.UnitAmount()
        //                            {
        //                                currency_code = "USD",
        //                                value = precio
        //                            }
        //                        }
        //                    }
        //                },
        //                new Models.Paypal_Order.PurchaseUnit()
        //                {
        //                    amount = new Models.Paypal_Order.Amount()
        //                    {
        //                        currency_code = "USD",
        //                        value = precio,
        //                        breakdown = new Models.Paypal_Order.Breakdown()
        //                        {
        //                            item_total = new Models.Paypal_Order.ItemTotal()
        //                            {
        //                                currency_code = "USD",
        //                                value = precio
        //                            }
        //                        }
        //                    }
        //                }
        //            },
        //            application_context = new ApplicationContext()
        //            {
        //                return_url = "https://www.youtube.com/watch?v=lbvkYag_wGE&t=2640s",
        //                cancel_url = "https://www.facebook.com"
        //            }
        //        };
        //        var json = JsonConvert.SerializeObject(orden);
        //        var data = new StringContent(json, Encoding.UTF8, "application/json");

        //        HttpResponseMessage response = await client.PostAsync("/v2/checkout/orders", data);

        //        status = response.IsSuccessStatusCode;
        //        if (status)
        //        {
        //            respuesta=response.Content.ReadAsStringAsync().Result;
        //        }
        //    }

        //    return Json(new {status=status, respuesta=respuesta},JsonRequestBehavior.AllowGet);

        //}


        [HttpPost]
        public async Task<JsonResult> Paypal(string precio, string ncuota)
        {
            bool status = false;
            string respuesta = string.Empty;

            try
            {
                // Configurar las credenciales de autenticación de PayPal
                var userName = "AceDg6yf6zlibcKhUCnXzhpKZ78r_CpkfuCSRJJQ08uQGj8KIJcIwY-yHYIgBX9u2YILhGDRJCr_z9vu";
                var password = "EBE03zsi9ey0KQvX9SBPui-PKjeD2eTVHK418QZL6ut8dMxTD8EysI61xcjS91tZITim0KFec3AwJbqe";

                // Construir el objeto de solicitud a la API de PayPal
                var orden = new
                {
                    intent = "CAPTURE",
                    purchase_units = new[]
                    {
                    new
                    {
                        items = new[]
                        {
                            new
                            {
                                name = "Numero de cuota: " + ncuota,
                                description = "Sistema de Prestamos Grupo 8A Cibertec",
                                quantity = "1",
                                unit_amount = new
                                {
                                    currency_code = "USD",
                                    value = precio
                                }
                            }
                        },
                        amount = new
                        {
                            currency_code = "USD",
                            value = precio,
                            breakdown = new
                            {
                                item_total = new
                                {
                                    currency_code = "USD",
                                    value = precio
                                }
                            }
                        }
                    }
                },
                    application_context = new
                    {
                        return_url = "http://localhost:56826/Prestatario/Abunt",
                        cancel_url = "http://localhost:56826/Home/Index"
                    }
                };

                // Convertir el objeto a formato JSON
                var json = JsonConvert.SerializeObject(orden);
                var data = new StringContent(json, Encoding.UTF8, "application/json");

WebSistemaPrestamos/WebSistemaPrestamos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Menu Principal</title>
    <link rel="icon" href="@Url.Content("~/img/logogeneral.png")" type="image/x-icon">

    @Styles.Render("~/Content/css")



    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">Sistema Prestamos</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto me-0 me-md-3 my-2 my-md-0">
            <li class="nav-item dropdown">

                @if (Session["Usuario"] != null)
                {
                    var usuario = (WebSistemaPrestamos.Models.Usuario)Session["Usuario"];
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user fa-fw"></i> @usuario.nombres @usuario.apellidos
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="@Url.Action("Salir","Acceso")">Cerrar Sesión</a></li>
                    </ul>
                }


            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">


                        <div class="sb-sidenav-menu-heading">Bienvenido </div>






                        <a class="nav-link" href="@Url.Action("Index","Home")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Principal
                        </a>

                        <div class="sb-sidenav-menu-heading">Mantenimiento</div>


                        @if (((WebSistemaPrestamos.Models.Usuario)Session["Usuario"]).orol.idrol == 1)
                        {

                            <a class="nav-link" href="@Url.Action("Index","Prestatario")">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Solicitar Prestamo
                            </a>


                            <a class="nav-link" href="@Url.Action("Vermisprestamos","Prestatario")">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Ver solicitudes
                            </a>

                            <a class="nav-link" href="@Url.Action("Abunt","Prestatario")">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Paypal
                            </a>

                        }




                        @if (((WebSistemaPrestamos.Models.Usuario)Session["Usuario"]).orol.idrol == 3)
                        {
                            <a class="nav-link" href="@Url.Action("Index","Prestamista")">
                                <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                                Prestatario
                            </a>

                            <a class="nav-link" href="@Url.Action("AprobarPrestamos","Prestamista")">
                                <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                                Aprobar Solicitudes
                            </a>

                        }

                        @if (((WebSistemaPrestamos.Models.Usuario)Session["Usuario"]).orol.idrol == 2)
                        {
                            <a class="nav-link" href="@Url.Action("Index","JefePrestamista")">
                                <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                                Prestamista
                            </a>
                        }
                        @if (((WebSistemaPrestamos.Models.Usuario)Session["Usuario"]).orol.idrol == 4)
                        {
                            <a class="nav-link" href="@Url.Action("Index","Inversionista")">
                                <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                                Jefe de Prestamista
                            </a>
                        }
                        @if (((WebSistemaPrestamos.Models.Usuario)Session["Usuario"]).orol.idrol == 5)
                        {
                            <a class="nav-link" href="@Url.Action("Index","Administrador")">
                                <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                                Prestamistas
                            </a>
                        }
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                @RenderBody()
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Derechos Reservados 2024</div>
                        <div>
                            <a href="#">Politicas y Privacidad</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/complementos")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>